all:
	g++ main.cpp carta.cpp baralho.cpp jogador.cpp pessoa.cpp botFacil.cpp botMedio.cpp botDificil.cpp botProf.cpp botImpossivel.cpp gamecontrol.cpp personalizar_baralho.cpp -o main -Wall -Wextra -std=c++0x -pthread
run:
	./main	